### ISSUE TITLE
Suricata list of TOP IP

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/scirius#36]
Hi,

Would be great if we could also have the list of TOP SOURCE IP and another list of TOP DEST IP when viewing Suricata alerts.
The current view only shows volume over timeline, which is great but does not give enough information.

Thanks.
B.

**Comment by pevma** [comment]
I think should be part of the detailed, drill down dashboards that are available after you click on the drop down icon at the top right corner(in SELKS for example).

**Comment by bugsland** [comment]
Hi Pevma, 
I am not sure I understand what you mean, did you mean the top *left* corner? and the links to the SELKS dashboard?
What I meant was to get that list of Top IP within Scirius as this would add more context to any rules you review on that Scirius GUI. Right now you only get timeline info, which is a good start, but doesn't mean much because you can't tell which of your local IP is affected (as a src or dst). 
Having a list of top IP related to a Suricata alert right into Scirius would make using Scirius more meaningful. If that could be coupled to a two way link to SELKS then even better.

Right now, if I start in Scirius, look at say the last 6h alert, drill down the different circles and identify a rule of interest I am ... stuck. I can see what the rule was looking for, when it was hit (timeline) and how many times. But I have no idea which IP were targeted and were it came from. 
So I then have to take note of the Suricata alert, go to SELKS and play with my filtering all other again.
It would flow better if 
a) I already had an idea of what IPs were involved (I am repeating myself I think here :)
b) I could then go back and forth between Selks and Scirius

**Comment by pevma** [comment]
Yes I meant the Kibana dashboards  - in order to drill  down in a lot more details (including the info you are after in the ALERTS dashboard).

**Comment by regit** [comment]
I've just pushed something alike to master: the rule page is now displaying the lists of source and destination IP that the alert generated by the rule.

**Comment by b-u-g-s** [comment]
Sounds great. Will try to test ASAP. Not really on topic but... any ideas when SELKS v3.0 will be out? :)

**Comment by regit** [comment]
Pushed and tested. Closing issue.
