### ISSUE TITLE
Django Upgrade?

### ISSUE THREAD

**Issue by b-u-g-s** [StamusNetworks/scirius#40]
Hi,

I noticed SELKS ships with Django version 1.6.6, is it tight to Debian Jessie?
I am asking because looking at the Django website to understand a bit more how Scirius is built there is a warning stating that users should upgrade to 1.8.3 due to security issues in older version.

Wondering if we can upgrade to that latest version or if doing so is going to break Scirius?
B.

**Comment by pevma** [comment]
It is build that way - https://github.com/StamusNetworks/SELKS/blob/master/staging/config/hooks/chroot-inside-Debian-Live.chroot#L19
It was due to a conflict (if I remember correctly). 
Would be thankful if you could please try and let us know if any potential issues arise actually.

**Comment by b-u-g-s** [comment]
Thanks Pevma, thats a very useful link! especialyl for someone like me who likes to look under the hood :)

So, I have upgraded to the latest version of Django using the following command:
pip install django==1.8.3 django-tables2 South GitPython pyinotify flup

Rebooted my VM (probably didnt have to)

Went to the SELKS dashboard and... yup there is a conflict indeed!
But that's super easy to fix, the error is 
"Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated"
Googling the error pointed me to this article:

http://stackoverflow.com/questions/28306288/removedindjango18warning-creating-a-modelform-without-either-the-fields-attri

So basically it seems an argument (Field or Exclude) is needed since version 1.8

Looking at the trace error in the browser you can identify the file that triggered that error:
/opt/selks/scirius/rules/form.py

You can see there is a line with no "field" or "exclude"
class SystemSettingsForm(forms.ModelForm):
    class Meta:
        model = SystemSettings
 
So if you add the following line under "model = SystemSettings":
class SystemSettingsForm(forms.ModelForm):
    class Meta:
        model = SystemSettings
        fields = '__all__'

save the file, reload the dashboard...
Everything seems to work fine! 
Not sure what else I need to do for being sure there is no other conflict but it seems OK to me now.
Will let you know in a few days, if anything else needs fixing (because it seems a bit too easy to be honest! :)

**Comment by b-u-g-s** [comment]
If you can tell me what you use Django for, I can try to stress test it by the way. I.e.: to do certain actions or load certain pages.

**Comment by regit** [comment]
Hi,
OK good. This bug is already fixed in git. Really need to make a release once deactivate is fixed.
Le 22 juil. 2015 6:35 PM, Bugs <notifications@github.com> a écrit :Thanks Pevma, thats a very useful link! especialyl for someone like me who likes to look under the hood :)

So, I have upgraded to the latest version of Django using the following command:
pip install django==1.8.3 django-tables2 South GitPython pyinotify flup

Rebooted my VM (probably didnt have to)

Went to the SELKS dashboard and... yup there is a conflict indeed!
But that's super easy to fix, the error is 
"Creating a ModelForm without either the 'fields' attribute or the 'exclude' attribute is deprecated"
Googling the error pointed me to this article:

http://stackoverflow.com/questions/28306288/removedindjango18warning-creating-a-modelform-without-either-the-fields-attri

So basically it seems an argument (Field or Exclude) is needed since version 1.8

Looking at the trace error in the browser you can identify the file that triggered that error:
/opt/selks/scirius/rules/form.py

You can see there is a line with no "field" or "exclude"
class SystemSettingsForm(forms.ModelForm):
    class Meta:
        model = SystemSettings

So if you add the following line under "model = SystemSettings":
class SystemSettingsForm(forms.ModelForm):
    class Meta:
        model = SystemSettings
        fields = 'all'

save the file, reload the dashboard...
Everything seems to work fine! 
Not sure what else I need to do for being sure there is no other conflict but it seems OK to me now.
Will let you know in a few days, if anything else needs fixing (because it seems a bit too easy to be honest! :)

**Comment by regit** [comment]
Closing that issue as latest git has a fixed version.
